Count,Message,Traceback,Nodes
88,cannot access local variable 'header' where it is not associated with a value,"  File ""/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py"", line 696, in mytask
    self.client.qianfan_request(
  File ""/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py"", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py"", line 346, in _request_internal
    'headers':header,
              ^^^^^^
","MacBook-Pro.local_ca3093a24fed4c15ba543665b537a2f1, MacBook-Pro.local_e95065a1602f45ff8cebc82dd1e8f3e9, MacBook-Pro.local_af6f5f8ca6a9422ba8aa52dc7a9c2b23, MacBook-Pro.local_e07f87b5e8cf4c7f9edc27cb2ca79cf3, MacBook-Pro.local_1956e413bd694c01a626dce83851c969, MacBook-Pro.local_1e9ecbc6d0ef4d37b19bc5d92b21c48d, MacBook-Pro.local_d8cf71ac6b68441592682eb1f40884c5, MacBook-Pro.local_21abf53018884ab8a9efb7a607bf27ef, MacBook-Pro.local_1f503fc657224660a88ce48fb45a8474, MacBook-Pro.local_56f15b90d91744f7b0b7f6cdabee09ef"
2,Object of type _GenericAlias is not JSON serializable,"  File ""/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py"", line 696, in mytask
    self.client.qianfan_request(
  File ""/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py"", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py"", line 350, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py"", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File ""/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py"", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py"", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File ""/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py"", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
","MacBook-Pro.local_1956e413bd694c01a626dce83851c969, MacBook-Pro.local_e95065a1602f45ff8cebc82dd1e8f3e9"
